
backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "/public/images"
public_folder: "/public/images"
search: false
logo_url: https://cdn.weckmann.me/wkmn.png
display_url: https://www.savanna.today
site_url: https://www.savanna.today

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Blog"
    name: "blog"
    folder: "/posts"
    create: true
    editor:
      preview: false
    slug: "{{slug}}-{{origin-date}}" # Set to {{year}}-{{month}}-{{daye}} when removing date object
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "desc", widget: "string" }
      - { label: "Date", name: "origin-date", widget: "string" } # remove date after all caught up on posts
      - { label: "Image", name: "image", widget: "string" }