backend:
  name: github
  repo: clarkhacks/savannavon
  branch: master
  site_domain: www.savanna.today
media_folder: "images/uploads"
collections:
  - name: "post" # Used in routes, e.g. /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}-{{year}}-{{month}}-{{day}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "desc", widget: "markdown"}
      - {label: "Image", name: "image", widget: "string"}
